
- name: Ensure pack directory exists
  file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0750
  loop:
    - "{{ nvim_dir }}"
    - "{{ plugin_dir }}"
- name: Deploy plugins
  git:
    dest: "{{ plugin_dir}}/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: yes
    update: yes
  loop:
  - name: vim-textobj-user
    url: https://github.com/kana/vim-textobj-user
  - name: vim-textobj-sentence
    url: https://github.com/preservim/vim-textobj-sentence
  - name: vim-textobj-quote
    url: https://github.com/preservim/vim-textobj-quote 
  - name: vim-pandoc-syntax
    url: https://github.com/vim-pandoc/vim-pandoc-syntax
  - name: vim-pandoc
    url: https://github.com/vim-pandoc/vim-pandoc
  - name: zen-mode
    url: https://github.com/folke/zen-mode.nvim 
