---
- name: Config Vim plugins on local machine
  hosts: localhost
  gather_facts: yes
  become: no

  vars:
    vim_dir: "{{ ansible_env .HOME }}/.vim"
    vimrc:  "{{ ansible_env .HOME }}/.vimrc"

  tasks:
    - name: Install required packages
      package:
        name:
          - vim-enhanced
          - git
          - powerline-fonts
          - fzf
        state: installed
      become: yes
    - name: Ensure .vim/pack directory exists
      file:
        path: "{{ item }}"
        state: directory
        recurse: no
        mode: 0750
      loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/pack/basic/start"
    - name: Deploy plugins
      git:
        dest: "{{ vim_dir}}/pack/bundle/start/{{ item.name }}"
        repo: "{{ item.url }}"
        clone: yes
        update: yes
        recursive: no
      loop:
      - name: surround-vim
        url: https://github.com/tpope/vim-surround
      - name: vim-airline
        url: https://github.com/vim-airline/vim-airline
      - name: vim-airline-themes
        url: https://github.com/vim-airline/vim-airline-themes
      - name: fzf-vim
        url: https://github.com/junegunn/fzf.vim
      - name: vim-gitgutter
        url: https://github.com/airblade/vim-gitgutter
      - name: vim-fugitive
        url: https://github.com/tpope/vim-fugitive
      - name: vim-solarized8
        url: https://github.com/lifepillar/vim-solarized8
    
  # Provisioning .vimrc
    - name: Ensure certain .vimrc settings exist
      lineinfile:
        path: "{{ vimrc }}"
        regexp: '{{item.from}}'
        line: '{{item.to}}'
        state: present
        create: yes
      with_items:
        - from: '^let g:airline_powerline_fonts ='
          to: let g:airline_powerline_fonts = 1
        - from: '^let g:airline_theme ='
          to: let g:airline_theme = 'solarized_flood'
        - from: '^set termguicolors'
          to: set termguicolors 
        - from: '^set background ='
          to: set background=dark
        - from: '^colorscheme'
          to: colorscheme solarized8_flat
        - from: '^colorscheme'
          to: colorscheme solarized8_flat
