---
- name: Config Vim plugins on local machine
  hosts: localhost
  gather_facts: yes
  become: no

  vars:
    vim_dir: "{{ ansible_env .HOME }}/.vim"
    vimrc:  "{{ ansible_env .HOME }}/.vimrc"

  tasks:
    - name: Install required packages
      package:
        name:
          - vim-enhanced
          - git
          - powerline-fonts
          - fzf
        state: installed
      become: yes
    - name: Ensure .vim/pack directory exists
      file:
        path: "{{ item }}"
        state: directory
        recurse: no
        mode: 0750
      loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/pack"
    - name: Deploy plugins
      git:
        dest: "{{ vim_dir}}/pack/{{ item.name }}"
        repo: "{{ item.url }}"
        clone: yes
        update: yes
        recursive: no
      loop:
      - name: vim-airline
        url: https://github.com/vim-airline/vim-airline
      - name: fzf-vim
        url: https://github.com/junegunn/fzf.vim
      - name: vim-gitgutter
        url: https://github.com/airblade/vim-gitgutter
      - name: vim-fugitive
        url: https://github.com/tpope/vim-fugitive
