---
- name: Ensure pack directory exists
  file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0750
  loop:
    - "{{ nvim_dir }}"
    - "{{ plugin_dir }}"

- name: Deploy plugins
  git:
    dest: "{{ plugin_dir}}/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: yes
    update: yes
  loop:
  - name: vim-fugitive
    url: https://github.com/tpope/vim-fugitive 
  - name: vim-surround
    url: https://github.com/tpope/vim-surround
  - name: vim-gitgutter
    url: https://github.com/airblade/vim-gitgutter
  - name: fzf.vim
    url: https://github.com/junegunn/fzf.vim
  - name: vim-airline
    url: https://github.com/vim-airline/vim-airline
  - name: vim-dirvish
    url: https://github.com/justinmk/vim-dirvish
