---
- name: Ensure pack directory exists
  file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0750
  loop:
    - "{{ nvim_dir }}"
    - "{{ plugin_dir }}"
- name: Deploy plugins
  git:
    dest: "{{ plugin_dir}}/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: yes
    update: yes
  loop:
  - name: vim-airline-themes
    url: https://github.com/vim-airline/vim-airline-themes 
  - name: vim-solarized8
    url: https://github.com/lifepillar/vim-solarized8

