---
- name: Config Vim plugins on local machine
  hosts: localhost
  gather_facts: yes
  become: no

  vars:
    vim_dir: "{{ ansible_env .HOME }}/.vim"
    vimrc:  "{{ ansible_env .HOME }}/.vimrc"

  tasks:
    - name: Install required packages
      package:
        name:
          - vim-enhanced
          - git
          - powerline-fonts
          - fzf
        state: installed
      become: yes
    - name: Ensure .vim/pack directory exists
      file:
        path: "{{ item }}"
        state: directory
        recurse: no
        mode: 0750
      loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/pack/bundle/start"
    - name: Deploy plugins
      git:
        dest: "{{ vim_dir}}/pack/bundle/start/{{ item.name }}"
        repo: "{{ item.url }}"
        clone: yes
        update: yes
        recursive: no
      loop:
      - name: surround-vim
        url: https://github.com/tpope/vim-surround
      - name: vim-airline
        url: https://github.com/vim-airline/vim-airline
      - name: vim-airline-themes
        url: https://github.com/vim-airline/vim-airline-themes
      - name: fzf-vim
        url: https://github.com/junegunn/fzf.vim
      - name: vim-gitgutter
        url: https://github.com/airblade/vim-gitgutter
      - name: vim-fugitive
        url: https://github.com/tpope/vim-fugitive
      - name: vim-solarized8
        url: https://github.com/lifepillar/vim-solarized8
      - name: vim-terraform
        url: https://github.com/hashivim/vim-terraform

    # Provisioning .vimrc
    - name: Populate g:airline_symbols dictionary
      lineinfile:
        path: "{{ vimrc }}"
        regex: '^let g:airline_powerline_fonts =' 
        line: let g:airline_powerline_fonts = 1
        create: yes
    - name: Enable airline powerline support
      lineinfile:
        path: "{{ vimrc }}"
        regex: '^let g:airline_theme ='
        line: let g:airline_theme = 'solarized_flood'
        create: yes 
    - name: Enable true color support
      lineinfile:
        path: "{{ vimrc }}"
        line: set termguicolors
        create: yes 
    - name: Set background to dark
      lineinfile:
        path: "{{ vimrc }}"
        regex: '^set background ='
        line: set background=dark
        create: yes 
    - name: Use Solarized8 colorscheme
      lineinfile:
        path: "{{ vimrc }}"
        regex: '^colorscheme'
        line: colorscheme solarized8_flat
        create: yes 
